"""add notification settings

Revision ID: c511ac1c9d5f
Revises: 001_add_chat_tables
Create Date: 2026-09-01 02:12:46.916600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c511ac1c9d5f'
down_revision: Union[str, None] = '001_add_chat_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_mappings', 'description',
               existing_type=mysql.VARCHAR(length=255),
               comment='模型描述',
               existing_comment='æ¨¡åž‹æ\x8f\x8fè¿°',
               existing_nullable=True)
    op.alter_column('model_mappings', 'price_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('token', 'request', name='pricetype'),
               comment='计费类型',
               existing_comment='è®¡è´¹ç±»åž‹',
               existing_nullable=False,
               existing_server_default=sa.text("'token'"))
    op.alter_column('model_mappings', 'price_per_1k_input',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='每千输入token价格(单位:元)',
               existing_comment='æ¯\x8få\x8dƒè¾“å…¥tokenä»·æ\xa0¼(å\x8d•ä½\x8d:å…ƒ)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('model_mappings', 'price_per_1k_output',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='每千输出token价格(单位:元)',
               existing_comment='æ¯\x8få\x8dƒè¾“å‡ºtokenä»·æ\xa0¼(å\x8d•ä½\x8d:å…ƒ)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('model_mappings', 'price_per_request',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='每次请求价格(单位:元)',
               existing_comment='æ¯\x8fæ¬¡è¯·æ±‚ä»·æ\xa0¼(å\x8d•ä½\x8d:å…ƒ)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('provider_quotas', 'raw_data',
               existing_type=mysql.TEXT(),
               comment='原始API响应数据',
               existing_nullable=True)
    op.alter_column('providers', 'group_id',
               existing_type=mysql.VARCHAR(length=64),
               comment='供应商Group ID，用于MiniMax等需要分组ID的API',
               existing_comment='ä¾›åº”å•†Group IDï¼Œç”¨äºŽMiniMaxç\xad‰éœ€è¦\x81åˆ†ç»„IDçš„API',
               existing_nullable=True)
    op.alter_column('providers', 'models',
               existing_type=mysql.TEXT(),
               comment='同步到的模型列表(JSON数组)',
               existing_comment='å\x90Œæ\xad¥åˆ°çš„æ¨¡åž‹åˆ—è¡¨(JSONæ•°ç»„)',
               existing_nullable=True)
    op.alter_column('providers', 'last_models_sync_at',
               existing_type=mysql.DATETIME(),
               comment='最后模型同步时间',
               existing_comment='æœ€å\x90Žæ¨¡åž‹å\x90Œæ\xad¥æ—¶é—´',
               existing_nullable=True)
    op.alter_column('providers', 'enabled_models',
               existing_type=mysql.TEXT(),
               comment='启用的模型映射ID列表(JSON数组)',
               existing_comment='å\x90¯ç”¨çš„æ¨¡åž‹æ˜\xa0å°„IDåˆ—è¡¨(JSONæ•°ç»„)',
               existing_nullable=True)
    op.add_column('users', sa.Column('quota_low_alert', sa.Boolean(), nullable=True, comment='额度不足通知'))
    op.add_column('users', sa.Column('quota_change_alert', sa.Boolean(), nullable=True, comment='额度变动通知'))
    op.add_column('users', sa.Column('daily_report', sa.Boolean(), nullable=True, comment='每日用量报表'))
    op.alter_column('users', 'model_group_ids',
               existing_type=mysql.TEXT(),
               comment='允许使用的模型分组ID列表，JSON数组',
               existing_comment='å…\x81è®¸ä½¿ç”¨çš„æ¨¡åž‹åˆ†ç»„IDåˆ—è¡¨',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'model_group_ids',
               existing_type=mysql.TEXT(),
               comment='å…\x81è®¸ä½¿ç”¨çš„æ¨¡åž‹åˆ†ç»„IDåˆ—è¡¨',
               existing_comment='允许使用的模型分组ID列表，JSON数组',
               existing_nullable=True)
    op.drop_column('users', 'daily_report')
    op.drop_column('users', 'quota_change_alert')
    op.drop_column('users', 'quota_low_alert')
    op.alter_column('providers', 'enabled_models',
               existing_type=mysql.TEXT(),
               comment='å\x90¯ç”¨çš„æ¨¡åž‹æ˜\xa0å°„IDåˆ—è¡¨(JSONæ•°ç»„)',
               existing_comment='启用的模型映射ID列表(JSON数组)',
               existing_nullable=True)
    op.alter_column('providers', 'last_models_sync_at',
               existing_type=mysql.DATETIME(),
               comment='æœ€å\x90Žæ¨¡åž‹å\x90Œæ\xad¥æ—¶é—´',
               existing_comment='最后模型同步时间',
               existing_nullable=True)
    op.alter_column('providers', 'models',
               existing_type=mysql.TEXT(),
               comment='å\x90Œæ\xad¥åˆ°çš„æ¨¡åž‹åˆ—è¡¨(JSONæ•°ç»„)',
               existing_comment='同步到的模型列表(JSON数组)',
               existing_nullable=True)
    op.alter_column('providers', 'group_id',
               existing_type=mysql.VARCHAR(length=64),
               comment='ä¾›åº”å•†Group IDï¼Œç”¨äºŽMiniMaxç\xad‰éœ€è¦\x81åˆ†ç»„IDçš„API',
               existing_comment='供应商Group ID，用于MiniMax等需要分组ID的API',
               existing_nullable=True)
    op.alter_column('provider_quotas', 'raw_data',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='原始API响应数据',
               existing_nullable=True)
    op.alter_column('model_mappings', 'price_per_request',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='æ¯\x8fæ¬¡è¯·æ±‚ä»·æ\xa0¼(å\x8d•ä½\x8d:å…ƒ)',
               existing_comment='每次请求价格(单位:元)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('model_mappings', 'price_per_1k_output',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='æ¯\x8få\x8dƒè¾“å‡ºtokenä»·æ\xa0¼(å\x8d•ä½\x8d:å…ƒ)',
               existing_comment='每千输出token价格(单位:元)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('model_mappings', 'price_per_1k_input',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='æ¯\x8få\x8dƒè¾“å…¥tokenä»·æ\xa0¼(å\x8d•ä½\x8d:å…ƒ)',
               existing_comment='每千输入token价格(单位:元)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('model_mappings', 'price_type',
               existing_type=sa.Enum('token', 'request', name='pricetype'),
               type_=mysql.VARCHAR(length=20),
               comment='è®¡è´¹ç±»åž‹',
               existing_comment='计费类型',
               existing_nullable=False,
               existing_server_default=sa.text("'token'"))
    op.alter_column('model_mappings', 'description',
               existing_type=mysql.VARCHAR(length=255),
               comment='æ¨¡åž‹æ\x8f\x8fè¿°',
               existing_comment='模型描述',
               existing_nullable=True)
    # ### end Alembic commands ###
